name: Continuous Integration

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
      fail-fast: false

    name: PHP ${{ matrix.php-versions }} Test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl
        ini-values: post_max_size=256M, max_execution_time=300, memory_limit=512M
        coverage: none
        tools: composer:v2

    - name: Debug Info
      run: |
        php -v
        php -m
        composer -V
        pwd
        ls -la

    - name: Install Composer Dependencies
      run: |
        composer install --no-dev --no-progress --prefer-dist
        composer require --dev phpunit/phpunit:"^9.5" --with-all-dependencies

    - name: Syntax Check
      run: |
        echo "Checking PHP Syntax..."
        find app -type f -name '*.php' -print0 | xargs -0 -n1 php -l
        
    - name: Install Code Quality Tools
      run: |
        composer require --dev squizlabs/php_codesniffer wp-coding-standards/wpcs
        vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs

    - name: Run PHPCS
      run: |
        echo "Checking Coding Standards..."
        vendor/bin/phpcs --standard=WordPress --extensions=php --ignore=*/vendor/*,*/tests/* app/

    - name: Run Unit Tests
      run: |
        echo "Running Unit Tests..."
        vendor/bin/phpunit --no-coverage --testsuite=unit tests/unit/SampleTest.php

    - name: Test Summary
      run: |
        echo "=== Test Summary ==="
        echo "PHP Version: $(php -v | head -n1)"
        echo "Composer Version: $(composer -V)"
        echo "All tests completed successfully!"