name: Continuous Integration

on:
  push:
    branches: [ master, develop ]

jobs:
  syntax:
    name: PHP Syntax Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: List PHP files
        run: |
          echo "Listing PHP files..."
          find app -type f -name '*.php' -ls
          
      - name: Check Main Plugin File
        run: |
          echo "Checking main plugin file..."
          php -l learndash-nbcs.php
          
      - name: Check Core Files
        run: |
          echo "Checking core files..."
          for file in app/clss/*.php; do
            echo "Checking $file"
            php -l "$file" || exit 1
          done
          
      - name: Check Function Files
        run: |
          echo "Checking function files..."
          for file in app/func/*.php; do
            echo "Checking $file"
            php -l "$file" || exit 1
          done

  quality:
    name: Code Quality
    needs: syntax
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2, phpcs
          
      - name: Install PHPCS
        run: |
          composer require --dev squizlabs/php_codesniffer wp-coding-standards/wpcs
          vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs
          
      - name: Show PHPCS Config
        run: |
          echo "PHPCS Configuration:"
          vendor/bin/phpcs -i
          vendor/bin/phpcs --config-show
          
      - name: Run PHPCS Analysis
        run: |
          echo "Running code analysis..."
          vendor/bin/phpcs \
            --standard=phpcs.xml \
            --report=summary,full \
            --colors \
            --warning-severity=0 \
            --ignore=*/vendor/*,*/tests/* \
            app/ || true
          
          echo "Checking for critical errors only..."
          vendor/bin/phpcs \
            --standard=phpcs.xml \
            --report=summary \
            --colors \
            --warning-severity=0 \
            --error-severity=1 \
            --ignore=*/vendor/*,*/tests/* \
            app/

  test-php:
    name: PHP ${{ matrix.php }} Tests
    needs: [syntax, quality]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1']
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=300, memory_limit=512M
          coverage: none
          tools: composer:v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install --no-dev --prefer-dist --no-progress

      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit:"^9.5" --with-all-dependencies

      - name: Run Tests
        run: vendor/bin/phpunit --no-coverage tests/unit/SampleTest.php

      - name: Test Summary
        run: |
          echo "=== Test Summary for PHP ${{ matrix.php }} ==="
          echo "PHP Version: $(php -v | head -n1)"
          echo "Composer Version: $(composer -V)"
          echo "Tests completed successfully!"