name: Continuous Integration

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']

    name: PHP ${{ matrix.php-versions }} Test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: xdebug
        tools: composer:v2, phpunit, php-cs-fixer, phpcs

    - name: Validate composer.json
      run: composer validate

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Dependencies
      run: |
        composer install --prefer-dist --no-progress
        rm -f composer.lock
        composer update --prefer-dist --no-progress

    - name: Check PHP Syntax
      run: find . -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l

    - name: Run PHP CodeSniffer
      run: vendor/bin/phpcs --standard=WordPress app/

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --coverage-text

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}